import furiaLogo from '../../public/furia-logo.svg'
import imperialLogo from '../../public/imperial-logo.svg'
import naviLogo from '../../public/navi-logo.svg'
import fazeLogo from '../../public/faze-logo.svg'
import fnaticLogo from '../../public/fnatic-logo.svg'
import liquidLogo from '../../public/liquid-logo.svg'
import heroicLogo from '../../public/heroic-logo.svg'
import skGamingLogo from '../../public/sk-gaming-logo.svg'
import glLogo from '../../public/gl-logo.svg'
import spiritLogo from '../../public/spirit-logo.svg'

export class BetsArray {
  betsCSGO = [
    {
      opponentLeft: 'FURIA',
      opponentRight: 'Imperial',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: furiaLogo.src,
      imgOpponentRight: imperialLogo.src,
      wLeft: { base: '10', lg: '10' },
      hLeft: { base: '10', lg: '10' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
    },
    {
      opponentLeft: 'Natus Vincere',
      opponentRight: 'fnatic',
      oddLeft: '1.18',
      oddRight: '1.94',
      imgOpponentLeft: naviLogo.src,
      imgOpponentRight: fnaticLogo.src,
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '12' },
      hRight: { base: '8', lg: '12' },
    },
    {
      opponentLeft: 'Heroic',
      opponentRight: 'Liquid',
      oddLeft: '1.35',
      oddRight: '1.68',
      imgOpponentLeft: heroicLogo.src,
      imgOpponentRight: liquidLogo.src,
      wLeft: { base: '8', lg: '12' },
      hLeft: { base: '8', lg: '12' },
      wRight: { base: '8', lg: '12' },
      hRight: { base: '8', lg: '12' },
    },
    {
      opponentLeft: 'FaZe',
      opponentRight: 'SK Gaming',
      oddLeft: '1.72',
      oddRight: '1.34',
      imgOpponentLeft: fazeLogo.src,
      imgOpponentRight: skGamingLogo.src,
      wLeft: { base: '8', lg: '10' },
      hLeft: { base: '8', lg: '10' },
      wRight: { base: '6', lg: '6' },
      hRight: { base: '6', lg: '6' },
    },
    {
      opponentLeft: 'GamerLegion',
      opponentRight: 'Spirit',
      oddLeft: '1.53',
      oddRight: '1.47',
      imgOpponentLeft: glLogo.src,
      imgOpponentRight: spiritLogo.src,
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '12' },
      hRight: { base: '8', lg: '12' },
    },
  ]

  betsLOL = [
    {
      opponentLeft: 'G2',
      opponentRight: 'LOUD',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
      avatarOpponentLeft: 'G 2',
      avatarOpponentRight: 'L D',
    },
    {
      opponentLeft: 'Red Kanids',
      opponentRight: 'Luminosity',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
      avatarOpponentLeft: 'R K',
      avatarOpponentRight: 'L O',
    },
    {
      opponentLeft: 'TSM',
      opponentRight: 'Liquid',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
      avatarOpponentLeft: 'T M',
      avatarOpponentRight: 'L Q',
    },
    {
      opponentLeft: 'OptiC Gaming',
      opponentRight: 'SK Gaming',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
      avatarOpponentLeft: 'O P',
      avatarOpponentRight: 'S K',
    },
    {
      opponentLeft: 'GO',
      opponentRight: 'Movistar Riders',
      oddLeft: '1.02',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '8', lg: '8' },
      hLeft: { base: '8', lg: '8' },
      wRight: { base: '8', lg: '8' },
      hRight: { base: '8', lg: '8' },
      avatarOpponentLeft: 'G O',
      avatarOpponentRight: 'M R',
    },
  ]

  betsFF = [
    {
      opponentLeft: 'Time FF 1',
      opponentRight: 'Time FF 2',
      oddLeft: '2.01',
      oddRight: '1.76',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time FF 3',
      opponentRight: 'Time FF 4',
      oddLeft: '1.64',
      oddRight: '1.29',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time FF 5',
      opponentRight: 'Time FF 6',
      oddLeft: '1.14',
      oddRight: '1.70',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time FF 7',
      opponentRight: 'Time FF 8',
      oddLeft: '1.31',
      oddRight: '1.56',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time FF 9',
      opponentRight: 'Time FF 10',
      oddLeft: '1.09',
      oddRight: '1.78',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
  ]

  betsR6 = [
    {
      opponentLeft: 'Time R6 1',
      opponentRight: 'Time R6 2',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time R6 3',
      opponentRight: 'Time R6 4',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time R6 5',
      opponentRight: 'Time R6 6',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time R6 7',
      opponentRight: 'Time R6 8',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time R6 9',
      opponentRight: 'Time R6 10',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
  ]

  betsValorant = [
    {
      opponentLeft: 'Time VLR 1',
      opponentRight: 'Time VLR 2',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time VLR 3',
      opponentRight: 'Time VLR 4',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time VLR 5',
      opponentRight: 'Time VLR 6',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time VLR 7',
      opponentRight: 'Time VLR 8',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time VLR 9',
      opponentRight: 'Time VLR 10',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
  ]

  betsDota2 = [
    {
      opponentLeft: 'Time DT2 1',
      opponentRight: 'Time DT2 2',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time DT2 3',
      opponentRight: 'Time DT2 4',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time DT2 5',
      opponentRight: 'Time DT2 6',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time DT2 7',
      opponentRight: 'Time DT2 8',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
    {
      opponentLeft: 'Time DT2 9',
      opponentRight: 'Time DT2 10',
      oddLeft: '1.34',
      oddRight: '1.89',
      imgOpponentLeft: '',
      imgOpponentRight: '',
      wLeft: { base: '', lg: '' },
      hLeft: { base: '', lg: '' },
      wRight: { base: '', lg: '' },
      hRight: { base: '', lg: '' },
    },
  ]
}
